# Generated by Django 6.0.6 on 2026-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
