# Generated by Django 6.0.6 on 2026-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_meal_is_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='preparation_style',
            field=models.CharField(choices=[('regular', 'Regular'), ('raw', 'Raw'), ('boiled', 'Boiled'), ('steamed', 'Steamed'), ('grilled', 'Grilled'), ('baked', 'Baked'), ('poached', 'Poached')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_style',
            field=models.CharField(choices=[('simple', 'Simple'), ('non_oily', 'Non-Oily')], default='simple', max_length=20),
        ),
    ]
