# Generated by Django 6.0.5 on 2026-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_plans_and_backfill'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditusagelog',
            new_name='subscriptio_user_id_51d341_idx',
            old_name='subscriptio_user_id_e3f3e0_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='subscriptio_user_id_7c893d_idx',
            old_name='subscriptio_user_id_8f1a2b_idx',
        ),
        migrations.AlterField(
            model_name='creditwallet',
            name='daily_allowance',
            field=models.PositiveIntegerField(default=1500, help_text="Snapshot of the plan's daily credit allowance."),
        ),
    ]
