# Generated by Django 6.0.5 on 2026-06-10 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('activity_type', models.CharField(choices=[('workout', 'Workout'), ('yoga', 'Yoga'), ('stretching', 'Stretching'), ('mobility', 'Mobility'), ('breathing', 'Breathing')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=150)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('engine_version', models.CharField(default='rule_based_v1', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('activity_type', models.CharField(choices=[('workout', 'Workout'), ('yoga', 'Yoga'), ('stretching', 'Stretching'), ('mobility', 'Mobility'), ('breathing', 'Breathing')], max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('is_timed', models.BooleanField(default=False, help_text='Check this for time-based exercises (e.g. plank, hold). Leave unchecked for rep-based exercises.')),
                ('equipment_needed', models.CharField(blank=True, default='None', help_text="Equipment required, e.g. 'Dumbbells', 'Resistance Band', or leave blank for none.", max_length=100)),
                ('default_sets', models.IntegerField(default=3)),
                ('default_reps', models.IntegerField(default=12)),
                ('default_duration_seconds', models.IntegerField(default=60)),
                ('default_rest_seconds', models.IntegerField(default=45)),
                ('calories_per_minute', models.FloatField(default=5)),
                ('youtube_url', models.URLField(blank=True, help_text='Paste the full YouTube URL, e.g. https://www.youtube.com/watch?v=abc123 OR the embed URL https://www.youtube.com/embed/abc123. The embed URL is auto-generated.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workout.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserFitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight')], max_length=30)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=30)),
                ('preferred_activity', models.CharField(choices=[('workout', 'Workout'), ('yoga', 'Yoga'), ('stretching', 'Stretching'), ('mobility', 'Mobility'), ('breathing', 'Breathing')], max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=150)),
                ('activity_type', models.CharField(choices=[('workout', 'Workout'), ('yoga', 'Yoga'), ('stretching', 'Stretching'), ('mobility', 'Mobility'), ('breathing', 'Breathing')], max_length=30)),
                ('duration_minutes', models.IntegerField()),
                ('generated_plan', models.JSONField(default=dict)),
                ('estimated_calories', models.FloatField(default=0)),
                ('ai_version', models.CharField(default='rule_based_v1', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='workout.userfitnessprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight')], max_length=30)),
                ('activity_type', models.CharField(choices=[('workout', 'Workout'), ('yoga', 'Yoga'), ('stretching', 'Stretching'), ('mobility', 'Mobility'), ('breathing', 'Breathing')], max_length=30)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=30)),
                ('available_minutes', models.IntegerField()),
                ('bmi', models.FloatField(default=0)),
                ('bmi_category', models.CharField(blank=True, max_length=30)),
                ('plan_json', models.JSONField(default=dict)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
