# Generated by Django 6.0.5 on 2026-06-07 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('remind_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('repeat', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('once', 'Once')], default='daily', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=8)),
                ('message', models.TextField()),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('sub_model', models.CharField(blank=True, max_length=64, null=True)),
                ('intent', models.CharField(blank=True, max_length=128, null=True)),
                ('report_type', models.CharField(blank=True, max_length=64, null=True)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='VoiceAssist_session_46e8b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='units', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=128)),
                ('utterance', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('response', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VoiceAssistant.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('preferred_language', models.CharField(default='en', max_length=8)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyFitnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('avg_steps', models.IntegerField(blank=True, null=True)),
                ('total_steps', models.IntegerField(blank=True, null=True)),
                ('avg_sleep', models.FloatField(blank=True, null=True)),
                ('avg_water', models.FloatField(blank=True, null=True)),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('avg_recovery', models.FloatField(blank=True, null=True)),
                ('avg_stress', models.FloatField(blank=True, null=True)),
                ('consistency_pct', models.FloatField(blank=True, help_text='% of days with ≥1 entry', null=True)),
                ('best_day', models.CharField(blank=True, max_length=16, null=True)),
                ('days_logged', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('session_id', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='FitnessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Browser session ID (localStorage)', max_length=128)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('steps', models.IntegerField(blank=True, help_text='Steps today', null=True)),
                ('distance_km', models.FloatField(blank=True, help_text='km walked/run', null=True)),
                ('sleep_hours', models.FloatField(blank=True, help_text='Total sleep hrs', null=True)),
                ('deep_sleep_hours', models.FloatField(blank=True, help_text='Deep sleep hrs', null=True)),
                ('rem_sleep_hours', models.FloatField(blank=True, help_text='REM sleep hrs', null=True)),
                ('bedtime', models.CharField(blank=True, max_length=16, null=True)),
                ('wake_time', models.CharField(blank=True, max_length=16, null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=16, null=True)),
                ('water_liters', models.FloatField(blank=True, help_text='Litres consumed', null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('calories_consumed', models.IntegerField(blank=True, null=True)),
                ('heart_rate_resting', models.IntegerField(blank=True, help_text='BPM resting', null=True)),
                ('heart_rate_max', models.IntegerField(blank=True, help_text='BPM max today', null=True)),
                ('heart_rate_avg', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, help_text='Set once, reused', null=True)),
                ('stress_score', models.IntegerField(blank=True, help_text='0–100', null=True)),
                ('recovery_score', models.IntegerField(blank=True, help_text='0–100', null=True)),
                ('mood', models.CharField(blank=True, choices=[('Great', 'Great'), ('Good', 'Good'), ('Neutral', 'Neutral'), ('Low', 'Low'), ('Terrible', 'Terrible')], max_length=16, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Input'), ('voice', 'Voice Input'), ('auto', 'Auto/Computed')], default='manual', max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitness Entry',
                'verbose_name_plural': 'Fitness Entries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['session_id', 'date'], name='VoiceAssist_session_188bca_idx')],
                'unique_together': {('session_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GoalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('metric', models.CharField(choices=[('steps', 'Daily Steps'), ('sleep_hours', 'Sleep Hours'), ('water_liters', 'Water (L)'), ('weight_kg', 'Weight (kg)'), ('calories_burned', 'Calories Burned'), ('recovery_score', 'Recovery Score')], max_length=32)),
                ('target_value', models.FloatField()),
                ('set_on', models.DateField(auto_now_add=True)),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session_id', 'metric')},
            },
        ),
    ]
